### ISSUE TITLE
Set up Travis to auto-build master branch

### ISSUE THREAD

**Issue by angela-li** [chircollab/chircollab.github.io#1]
Steps to do this:

- [x] Angela will enable Travis for repo
- [x] Include .travis.yml file in "website-source" branch, read [Blogdown docs here](https://bookdown.org/yihui/blogdown/travis-github.html)

**Comment by angela-li** [comment]
Note to future us: the `publishDir` is set to `docs` in [line 9 of config.toml](https://github.com/chircollab/chircollab.github.io/blob/50ff58db2761f241857bf676a047e93a8b28725d/config.toml#L9), so any configuration needs to replace `public` with `docs`. 

I.e. [line 28 of .travis.yml](https://github.com/chircollab/chircollab.github.io/blob/50ff58db2761f241857bf676a047e93a8b28725d/.travis.yml#L28) should be `local_dir: docs`.

**Comment by angela-li** [comment]
Very cool, we can see all the builds here: https://travis-ci.com/chircollab/chircollab.github.io/builds

**Comment by willdebras** [comment]
You can see the dozen of one line commits trying to get the app to deploy in the right place hahahah
