### ISSUE TITLE
Add Code of Conduct to website

### ISSUE THREAD

**Issue by angela-li** [chircollab/chircollab.github.io#2]
Use this Code of Conduct: https://github.com/RConsortium/RCDI-WG/blob/master/conduct/code-of-conduct.md

See old Chi R Unconf site for where to put this info: https://github.com/chirunconf/chirunconf.github.io/blob/website-source/content/coc.md

**Comment by angela-li** [comment]
As discussed in Sunday's organizer meeting, we would like to take out the phrase "In order to protect volunteers from abuse and burnout, we reserve the right to reject any report we believe to have been made in bad faith. Reports intended to silence legitimate criticism may be deleted without response." from the Code of Conduct.

Our main reasoning is that this sentence is in the CoC to protect us as organizers, and we believe the rest of the content of the CoC, without this sentence, will allow us to handle reports in an appropriate manner. Additionally, this text is taken from the RCDI-WG CoC, which has [recently been modified](https://github.com/RConsortium/RCDI-WG/commit/3070323cf553ef597faecfa5b48e5a91aad8a38c) to remove this text. As a standalone event, we would like to align with a larger organization.

@alexpghayes @willdebras @EmilyRiederer @skpurdue would you please confirm that you agree with this, and add any other discussion / justification that I missed?

**Comment by willdebras** [comment]
I agree with this modification.

**Comment by alexpghayes** [comment]
I'm on board following our conversation last Sunday.

**Comment by emilyriederer** [comment]
I agree with the change

**Comment by skpurdue** [comment]
I agree with this as well
