### ISSUE TITLE
Make a "For Participants" section

### ISSUE THREAD

**Issue by angela-li** [chircollab/chircollab.github.io#3]
Something obvious for participants to see the [Github page](https://github.com/chircollab/chircollab20) would be great!

**Comment by angela-li** [comment]
Adding a Wiki under the chircollab20 page and linking to that would also be helpful -- see [last year's wiki](https://github.com/chirunconf/chirunconf19/wiki) for ideas. You can copy over the content re: Schedule, and I'll update other tabs.

**Comment by willdebras** [comment]
forgot to close this :) Added wiki, linked on website
