### ISSUE TITLE
Update "Participants" section

### ISSUE THREAD

**Issue by angela-li** [chircollab/chircollab.github.io#4]
The following individuals are no longer available for the event due to personal matters. If we could update the Participants section to reflect this, that would be great!

- Kristi Angel
- Jonathan Keane
- Mara Averick

**Comment by angela-li** [comment]
Also @willdebras if you please add the following people who have RSVPed (they will be replacing R-Ladies who can’t attend):

- Gabi Cipriano
- Rui Chen 
- Brooke Anderson 

I think there are also some ppl who filled out the Acceptance Form late and haven’t been added to the site yet. Ack, sorry this is such a hassle.

**Comment by willdebras** [comment]
Participant list and their links and pictures updated in the config
